version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Evita sobrescrever node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: sh -c "npm install && npx nodemon server.js"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobrescrever node_modules
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  db:
    image: nouchka/sqlite3
    platform: linux/amd64
    container_name: sqlite-db
    volumes:
      - ./backend/src/db_data:/data
